start_holiday_mode:
  name: Start holiday mode
  description: Puts a Smol account into holiday mode. The entity should be `binary_sensor.smol_{{ACCOUNT_NAME}}_is_on_holiday`. 
  target:
    entity:
      integration: smol
      domain: binary_sensor
  fields:
    end_date_time:
      name: End datetime
      description: The datetime of when the holiday mode should end
      selector:
        datetime:

end_holiday_mode:
  name: End holiday mode
  description: Takes a Smol account out of holiday mode. The entity should be `binary_sensor.smol_{{ACCOUNT_NAME}}_is_on_holiday`. 
  target:
    entity:
      integration: smol
      domain: binary_sensor

change_next_charge_date:
  name: Change next charge date
  description: Changes the next charge date for a Smol subscription. The entity should be `sensor.smol_{{ACCOUNT_NAME}}_{{PRODUCT_ID}}_subscription_next_charge`. 
  target:
    entity:
      integration: smol
      domain: sensor
  fields:
    next_charge_date:
      name: Next charge date date
      description: The next charge date the subscription should be changed to
      selector:
        date: